alpha = 0.40
gamma = 0.50
epsilon = 0.99
min_epsilon = 0.05
epsilon_decay = 0.99
max_steps = 100  # Defined in the env, added here for info
transition_times = 1  # How many times run the planning module
LAST_MOVES_COUNT = 100  # For recording statistics
version = 'v0'
